### ISSUE TITLE
Rename titles (gft, tuinafval) key swapped

### ISSUE THREAD

**Issue by cedricmoers** [pippyn/Home-Assistant-Sensor-Ophaalkalender#24]
Hi pippyn, 

Thank you for making this component and also making the effort to make one for Belgium.
After installing I noticed that the GFT/Tuinafval calendar was nog working so I looked into the sensor.py file and found that the key seems swapped:

changing <'tuinafval': 'gft'> to <'gft': 'tuinafval'> solved the issue for me. I don't know if this will change anything for the dutch version.

Thanks

**Comment by FredericMa** [comment]
I just encountered the same issue.
The working solution for me is just putting gft instead of tuinafval in the yaml configuration.
This way, the renaming doesn't take place uses the naming of the returned json data which is GFT.
PR #21 actually 'solves' the same issue but it looks like the documentation is wrong instead of the code. In the documentation we should always use GFT instead of Tuinafval.

**Comment by pippyn** [comment]
You are right. Use GFT as a resource. In the next version you can use either one. I'll update the docs

**Comment by cedricmoers** [comment]
Hi @pippyn and @FredericMa ,
Thank you for looking into this issue and providing a solution.
